### ISSUE TITLE
[config] update template config to match new requirements

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/dapp-template#7]
Hi,

we need to update the config as specified [here](https://github.com/florianlenz/pangea-specs/blob/master/dapps/dapp_layout.md). 

The config should be moved to `package.json` under the key `pangea_dapp`.

**Comment by hunght** [comment]
I will do as the following:
1.  update Pangea command line both dapp:build and dapp:stream to read the package.json with the format like this 
```json
{
   "pangea_dapp": {
       "name": {"en-us": "send / request money", "de": "geld senden / anfordern"},
        "engine": "1.0.7",
        "icon_path": "path"
    }
}
```

2. And also should change  /build/dapp_build.json according to specs

**Comment by hunght** [comment]
Estimate: 1 day
